extends:
  - 'airbnb-base'
env:
  node: true
  browser: true
  es6: true
rules:
    no-console: off
    indent: ["error", 2]
    semi: "error"
    no-unused-vars: "warn"
    linebreak-style: ["error", "windows"]
    prefer-arrow-callback: ["off", { "allowNamedFunctions": true }]
    eol-last: ["error", "never"]
    func-names: ["off", "as-needed"]
    func-style: ["off", "declaration"]